---
title: "RMarkdown Class Schedule"
author: "Phichchaya Sutaporn"
date: "August 28, 2019"
output: html_notebook
---
# Class Schedule

### PSU 016: First-Year Seminar

PSU 016 is a first year siminar class. My instructor of this is class is Dr.Beckman. This class gives me a chance to learn about how to success in academic life, time management, also know more about statistics such as study options, jobs after graduate,grad school and etc. All of student in this class are majoring in statistic, so this is a good opportunity to get to know people who has similar goal and kind of see thing silimar as you do.

I attach a page about the importances of statistic the title is "10 Awesome Reasons Why Statistics Are Important" be open minded and read it, maybe you love love stat as I do ! [here's the link](https://medium.com/@john_marsh7/10-awesome-reasons-why-statistics-are-important-96b87e283640)!

I also want you to look at this statistics joke, you will love it (maybe haha)(http://www.mathfunny.com/images/mathjoke-haha-humor-math-meme-joke-pic-mathmeme-funnypics-pun-standarddeviation-statistics-norm-love.jpg)


### STAT 184: Introduction to R Programmaing

STAT 184 is an introduction to R course. I also have Dr.Beckman as an instructor (same as PSU016). We will learn R language which is a powerful source for statiscial analysis. I take this course even though I have no idea abiut this language before because I think it will give me many benefits for my future study and career

This is a link about R language for people who don't know R. This page will explain you about R language. So, please take a look. [here's the link](https://www.r-project.org/about.html)

Here is a picture showing why you should learn R language (https://hackernoon.com/hn-images/1*WSZpEbx1J71GL7KZ4BOONQ.jpeg)


### STAT 200: Elementary Statistics

I'm taking STAT200 with Dr. Matthew Reimherr.This is a class about basic concept of data collection, exploratory data analysis and statistical inference. I will earn 4 credits after I finished this class. This class is also a requirement for statistics major.

Here is a page that talks about what is statistics and how to understand elementary statistics [here's the link](https://www.statisticshowto.datasciencecentral.com/what-is-elementary-statistics/)

This is the picture that show jobs that people get after graduated in statistics major, so you can see kind of overview about careers that related to statistics! (https://www.tun.com/blog/wp-content/uploads/2019/04/Statistics-Major-Web.png)




